// Flashcards — frasi di incoraggiamento mostrate a fine sessione.
// Tutte declinate al femminile e SEMPRE positive: anche i punteggi bassi
// ricevono una frase dolce e motivante, mai un rimprovero.
// Aggiungine quante vuoi a ciascun gruppo. app.js sceglie l'array in base
// alla percentuale di risposte giuste e ne pesca una a caso:
//   PRAISE_PERFECT  -> 100% (nessun errore)
//   PRAISE          -> oltre il 90%
//   PRAISE_GOOD     -> 70% – 89%
//   PRAISE_OK       -> 50% – 69%
//   PRAISE_LOW      -> sotto il 50%
const PRAISE = [
  "Oltre il 90%, amore mio! Sei un fenomeno della natura, letteralmente.",
  "Bravissima patatina, queste domande non hanno avuto scampo.",
  "Più del 90% giuste, broccolina: il professore dovrebbe prendere appunti da te.",
  "Amore, hai spazzato via il quiz come un cinghiale tra i cespugli.",
  "Che genio sei, amore mio! La fauna italiana ti applaude.",
  "Patatina, con questo punteggio meriti una laurea ad honorem.",
  "Broccolina, più del 90%: sei nata per le scienze naturali.",
  "Sei stata spettacolare, amore. Continua così e ti mangi l'esame.",
  "Oltre il 90%, patatina mia: sei una piccola enciclopedia vivente.",
  "Amore mio, hai fatto faville! Ogni capriolo del bosco è fiero di te.",
  "Broccolina, questo punteggio è roba da campioni. Quanto sei in gamba!",
  "Brava amore! Più del 90%: la tua testolina è piena di cose belle.",
  "Patatina, hai dominato il quiz come una regina del sottobosco.",
  "Amore mio, 90% e oltre: la prova che lo studio paga (e che sei bellissima).",
  "Broccolina, sei un asso! Le domande ormai ti temono.",
  "Più del 90%, amore: ti meriti un bacio per ogni risposta giusta.",
  "Patatina, che cervellone! La biologia non ha segreti per te.",
  "Amore mio, hai stracciato tutti. Anche il cinghiale è impressionato.",
  "Broccolina, oltre il 90%: stai diventando una vera naturalista.",
  "Bravissima amore, sei sulla strada giusta per spaccare all'esame.",
  "Patatina, più del 90%: ogni neurone al posto giusto, complimenti!",
  "Amore, ti sei superata. Sei la mia scienziata preferita.",
  "Broccolina, con questo punteggio potresti insegnare tu, altro che studiare.",
  "Oltre il 90%, amore mio: sei una piccola grande mente della fauna.",
  "Patatina, hai fatto un figurone! Continua a brillare così.",
  "Amore, più del 90%: nemmeno un daino corre veloce quanto la tua mente.",
  "Broccolina, sei bravissima e lo sai. Questo quiz è tuo.",
  "Patatina mia, che soddisfazione vederti così preparata!",
  "Amore mio, oltre il 90%: la natura ti ha fatto bella e intelligente.",
  "Broccolina, hai centrato quasi tutto! Sei una macchina da studio.",
  "Più del 90%, amore: ogni risposta giusta è un passo verso l'esame superato.",
  "Patatina, sei un portento! Te lo dico col cuore.",
  "Amore mio, hai studiato da campionessa e si vede tutto.",
  "Broccolina, oltre il 90%: il bosco intero fa il tifo per te.",
  "Bravissima patatina, questa testolina vale oro.",
  "Amore, più del 90% giuste: sei semplicemente la migliore.",
  "Broccolina, che orgoglio! Stai volando con questo studio.",
  "Patatina, oltre il 90%: il capriolo ti nomina dottoressa onoraria.",
  "Amore mio, sei una stella. Continua a splendere così.",
  "Broccolina, hai dominato! Le scienze naturali sono pane per i tuoi denti.",
  "Più del 90%, patatina: il tuo cervello è in gran forma oggi!",
  "Amore, sei stata perfetta quasi ovunque. Ti adoro studiosa così.",
  "Broccolina mia, questo punteggio merita una festa.",
  "Patatina, oltre il 90%: sei la mia piccola enciclopedia di fauna.",
  "Amore mio, che prestazione! Nemmeno un lupo è furbo quanto te.",
  "Broccolina, più del 90%: sei nata per indossare il camice.",
  "Bravissima amore, ogni pagina studiata si sta trasformando in oro.",
  "Patatina, hai spaccato! Che orgoglio, il mio genietto.",
  "Amore mio, oltre il 90%: te lo meriti tutto questo successo.",
  "Broccolina, sei una forza della natura. Letteralmente, vista la materia.",
  "Più del 90%, amore: la tua mente è affilata come gli artigli di un'aquila.",
  "Patatina, complimenti! Hai il quiz in pugno.",
  "Amore mio, hai risposto come una vera esperta. Che orgoglio!",
  "Broccolina, oltre il 90%: continua così e l'esame è già tuo.",
  "Bravissima patatina, ti sei meritata un abbraccio gigante.",
  "Amore, più del 90%: sei intelligente quanto sei dolce.",
  "Broccolina, che bomba! Le domande non sapevano cosa le aspettava.",
  "Patatina mia, oltre il 90%: stai diventando un mostro di bravura.",
  "Amore mio, hai brillato. La fauna italiana ti incorona.",
  "Broccolina, più del 90% giuste: sei la mia campionessa del bosco.",
  "Più del 90%, amore: ogni cervo, daino e capriolo è fiero di te.",
  "Patatina, sei un fuoriclasse! Lo sapevo che ce l'avresti fatta.",
  "Amore mio, hai studiato col cuore e i risultati si vedono.",
  "Broccolina, oltre il 90%: ti meriti il podio, anzi il gradino più alto.",
  "Bravissima amore, sei la dimostrazione che impegno e bellezza convivono.",
  "Patatina, più del 90%: la tua memoria è una trappola perfetta.",
  "Amore mio, che spettacolo! Non sbagli un colpo.",
  "Broccolina, hai dominato il quiz come il cinghiale domina il bosco.",
  "Patatina, oltre il 90%: sei sempre più vicina al traguardo.",
  "Amore, sei stata bravissima. Ti voglio bene, genietta mia.",
  "Più del 90%, broccolina: la scienza ti scorre nelle vene.",
  "Patatina mia, complimenti! Questa testa pensa benissimo.",
  "Amore mio, oltre il 90%: ogni risposta giusta mi fa innamorare di più.",
  "Broccolina, sei una scheggia! La fauna non ha segreti per te.",
  "Bravissima amore, hai studiato come una leonessa e ruggito come tale.",
  "Patatina, più del 90%: il tuo impegno è semplicemente meraviglioso.",
  "Amore mio, che orgoglio averti come studiosa e come amore.",
  "Broccolina, oltre il 90%: stai diventando il numero uno.",
  "Patatina, hai fatto centro quasi ovunque. Sei fortissima!",
  "Amore, più del 90%: la natura ti ha dato testa e cuore.",
  "Broccolina, sei stata magnifica! Festeggiamo questo punteggio.",
  "Patatina mia, oltre il 90%: meriti tutto il bene del mondo.",
  "Amore mio, hai spaccato il quiz. Prossima tappa l'esame, e lo prendi.",
  "Broccolina, più del 90%: la tua bravura non smette di sorprendermi.",
  "Bravissima patatina, ogni domanda è caduta sotto i tuoi colpi.",
  "Amore, oltre il 90%: sei la mia piccola Darwin personale.",
  "Broccolina, che prestazione da urlo! Sei tutta da incorniciare.",
  "Patatina, più del 90%: il bosco ha una nuova campionessa, e sei tu.",
  "Amore mio, hai studiato benissimo. Te lo leggo nei risultati.",
  "Broccolina, oltre il 90%: continua a stupirmi così, ti prego.",
  "Più del 90%, amore: intelligente, dolce e pure preparata. Imbattibile.",
  "Patatina, complimenti dal profondo del cuore! Sei un fenomeno.",
  "Amore mio, hai dominato. Nemmeno la volpe è astuta quanto te.",
  "Broccolina, oltre il 90%: il tuo cervellino merita una medaglia.",
  "Bravissima patatina, questo è il punteggio di una vera scienziata.",
  "Amore, più del 90%: ogni minuto di studio è valso la pena.",
  "Broccolina, sei una meraviglia! Le scienze naturali ti adorano.",
  "Patatina mia, oltre il 90%: sei sempre più brava, sempre più mia.",
  "Amore mio, hai brillato come una stella nel cielo del bosco.",
  "Broccolina, più del 90% giuste: campionessa oggi, dottoressa domani. Ti adoro!",
];

// Riservate al punteggio PERFETTO (100%, nessun errore). Più sopra le righe.
const PRAISE_PERFECT = [
  "Perfetto, amore mio! Tutte giuste, nemmeno una virgola fuori posto: sei leggendaria.",
  "En plein, patatina! 100% tondo tondo, sei semplicemente perfetta.",
  "Broccolina, hai fatto cappotto: tutte corrette! Non esiste nessuna come te.",
  "100%, amore: hai dominato ogni singola domanda. Inchino totale.",
  "Patatina, punteggio pieno! Zero errori, classe infinita.",
  "Amore mio, è perfezione pura: non ne hai sbagliata una. Mostruoso!",
  "Broccolina, cento su cento! Sei ufficialmente un genio della fauna.",
  "Tutte giuste, patatina! Questa la incornicio: 100% di puro talento.",
  "Amore, hai centrato tutto. Il professore può solo applaudire in piedi.",
  "Perfetta perfetta perfetta, broccolina! Non ti ferma nessuno.",
  "100%, amore mio: sei una bestia rara e bellissima delle scienze naturali.",
  "Patatina, en plein assoluto! Hai studiato da dea e si vede.",
  "Cento su cento, broccolina: nemmeno un capriolo è veloce quanto la tua mente.",
  "Amore, percorso netto, zero sbavature. Sei nata per questo esame.",
  "Punteggio perfetto, patatina! Ti meriti il mondo intero (e un bacio enorme).",
  "Broccolina, hai fatto l'impossibile: tutte giuste. Ti amo, genietta.",
  "100%, amore mio: oggi la perfezione ha la tua faccia.",
  "Patatina, nessun errore! Sei un fenomeno, non ci sono altre parole.",
  "Amore, cappotto pieno: 100% di bravura e dolcezza. Imbattibile.",
  "Broccolina, hai stracciato il quiz senza pietà. Perfetta, semplicemente perfetta.",
  "Tutte corrette, amore mio! Sei la mia enciclopedia preferita, edizione perfetta.",
  "Patatina, 100% netto: oggi hai fatto la storia di questo quiz.",
  "Amore, zero errori e tanto cuore. Sei il numero uno, sempre.",
  "Broccolina, en plein! Lo sapevo che eri una campionessa assoluta.",
  "Cento su cento, patatina mia: nessuna studia (ed è bella) quanto te.",
  "Amore mio, perfezione totale! Il bosco intero si inchina alla sua regina.",
  "100%, broccolina: hai risposto come un libro stampato. Spettacolare!",
  "Patatina, non una sbagliata! Sei pura magia in versione studio.",
  "Amore, punteggio pieno: ti sei superata, e io ti adoro per questo.",
  "Broccolina, perfetto al 100%! Domani dottoressa, oggi già leggenda.",
];

// Punteggio buono (70% – 89%): brava davvero, ci sei quasi.
const PRAISE_GOOD = [
  "Più del 70%, amore mio! Sei proprio sulla strada giusta, continua così.",
  "Bravissima patatina, bel punteggio: ancora un pochino e le sbaragli tutte.",
  "Broccolina, te la cavi alla grande! La fauna italiana inizia a temerti.",
  "Amore, ottimo lavoro! Hai una base solida, l'esame è più vicino di quanto pensi.",
  "Patatina, sei brava davvero. Ripassa due cosine e sfiori la perfezione.",
  "Broccolina, più del 70%: testolina che funziona benissimo, complimenti!",
  "Amore mio, bel risultato! Ancora qualche giro e diventi imbattibile.",
  "Bravissima patatina, hai capito un sacco di roba. Ne sono fiero.",
  "Broccolina, ci sei quasi! Manca pochissimo per il punteggio da regina.",
  "Amore, sei in gamba! Questo punteggio dice che lo studio sta pagando.",
  "Patatina mia, ottimo! Un'altra sessione e voli oltre il 90%.",
  "Broccolina, più del 70% giuste: sei una piccola naturalista in crescita.",
  "Amore mio, bravissima! Hai dato del filo da torcere a queste domande.",
  "Patatina, gran bel lavoro. La strada è tutta in discesa da qui.",
  "Broccolina, te lo dico col cuore: stai studiando da campionessa.",
  "Amore, bel punteggio! Coltiva questa base e l'esame è tuo.",
  "Patatina mia, ci siamo quasi! Sei più preparata di quanto credi.",
  "Broccolina, più del 70%: ogni ripasso ti rende più forte. Avanti così!",
  "Amore mio, bravissima davvero. Un pizzico in più e arrivi in cima.",
  "Patatina, ottimo risultato! Il capriolo ti fa già l'occhiolino.",
  "Broccolina, sei brava e si vede. Continua a spingere, ci sei quasi.",
  "Amore, gran bella prova! La prossima sessione la spacchi ancora di più.",
];

// Punteggio discreto (50% – 69%): bella base, ora si sale.
const PRAISE_OK = [
  "Più della metà giuste, amore! Bella base: ora si sale piano piano.",
  "Bravissima patatina, hai superato la metà! Ripassa e vedrai che salto.",
  "Broccolina, ci stai prendendo la mano. Ogni sessione un passo avanti.",
  "Amore mio, buon inizio! Hai le idee giuste, basta solo affinarle.",
  "Patatina, più del 50%: il difficile è cominciare, e tu l'hai già fatto.",
  "Broccolina, sei sulla buona strada! Un altro ripasso e voli.",
  "Amore, mezzo quiz domato! Bravissima, ora il resto viene da sé.",
  "Patatina mia, hai una base solida. Coltivala e diventerà oro.",
  "Broccolina, oltre la metà giuste: stai imparando alla grande, fidati.",
  "Amore mio, dai che ci sei! Ancora un po' di studio e spicchi il volo.",
  "Patatina, buon lavoro! Ogni errore di oggi è una risposta giusta di domani.",
  "Broccolina, più del 50%: la testolina lavora, serve solo un altro giro.",
  "Amore, sei partita bene! Sono fiero di ogni risposta che hai azzeccato.",
  "Patatina mia, metà strada fatta. Il bosco crede in te, e io pure.",
  "Broccolina, ci stai arrivando! Ripassa con calma e i numeri salgono.",
  "Amore mio, bel passo avanti! Non mollare, stai migliorando davvero.",
  "Patatina, oltre la metà! Un altro ripassino e superi te stessa.",
  "Broccolina, sei in crescita. Le cose si stanno sistemando nella testolina.",
  "Amore, bravissima per l'impegno! Il risultato grosso è dietro l'angolo.",
  "Patatina mia, più del 50%: ottima base, ora costruiamoci sopra insieme.",
];

// Punteggio basso (sotto il 50%): qui niente rimproveri, solo dolcezza e
// incoraggiamento. L'obiettivo è farle venire voglia di riprovare.
const PRAISE_LOW = [
  "Amore mio, ogni grande naturalista è partita da qui. Sono fiero di te comunque.",
  "Patatina, non conta il punteggio: hai studiato, e questo vale tantissimo.",
  "Broccolina, oggi è solo il primo passo. La prossima volta andrà meglio, promesso.",
  "Amore, l'importante è esserci provata. Ti voglio bene esattamente uguale.",
  "Patatina mia, anche il cinghiale ha sbagliato sentiero prima di imparare. Avanti!",
  "Broccolina, niente sconforto: ogni errore di oggi è una lezione per domani.",
  "Amore mio, sei comunque la mia scienziata preferita. Riproviamo insieme?",
  "Patatina, un ripasso e questi numeri cambiano faccia. Credo in te, sempre.",
  "Broccolina, oggi pochi punti ma tanto cuore. Domani spacchi, vedrai.",
  "Amore, non ti scoraggiare: l'inizio è sempre il pezzo più in salita.",
  "Patatina mia, sei coraggiosa solo a metterti in gioco. Ne sono fiero.",
  "Broccolina, ci riproviamo con calma. Ogni capriolo impara a camminare cadendo.",
  "Amore mio, conta che ci hai messo impegno. Il resto arriva, fidati di me.",
  "Patatina, oggi è andata così, e va benissimo. Domani è un'altra sessione.",
  "Broccolina, ti abbraccio forte: un altro giro e questi numeri salgono di sicuro.",
  "Amore, nessuna paura del punteggio. Stai imparando, ed è la cosa che conta.",
  "Patatina mia, sei più brava di quanto dica questo numero. Riproviamo!",
  "Broccolina, piano piano si arriva lontano. Io sono qui a fare il tifo per te.",
  "Amore mio, oggi semini, domani raccogli. Continua a studiare, sei fortissima.",
  "Patatina, ti voglio bene a prescindere da ogni quiz. Forza, ci riproviamo insieme!",
];
